// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// concordance.cpp
integers concordance_naive_cpp(doubles x, doubles y);
extern "C" SEXP _jaspRegression_concordance_naive_cpp(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(concordance_naive_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y)));
  END_CPP11
}
// concordance.cpp
integers concordance_fenwick_cpp(doubles x, doubles y);
extern "C" SEXP _jaspRegression_concordance_fenwick_cpp(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(concordance_fenwick_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_jaspRegression_concordance_fenwick_cpp", (DL_FUNC) &_jaspRegression_concordance_fenwick_cpp, 2},
    {"_jaspRegression_concordance_naive_cpp",   (DL_FUNC) &_jaspRegression_concordance_naive_cpp,   2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_jaspRegression(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
