# Generated by cpp11: do not edit by hand

concordance_naive_cpp <- function(x, y) {
  .Call(`_jaspRegression_concordance_naive_cpp`, x, y)
}

concordance_fenwick_cpp <- function(x, y) {
  .Call(`_jaspRegression_concordance_fenwick_cpp`, x, y)
}
