# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concordanceVector_cpp <- function(x, y) {
    .Call('_jaspRegression_concordanceVector_cpp', PACKAGE = 'jaspRegression', x, y)
}

